spring:
  application:
    name: qi-ai-code-father-backend
server:
  port: 8527
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.wqa.qiaicodefather.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
